spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/messagesdb}
spring.datasource.username=${DB_USERNAME:jeroen}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false